### ISSUE TITLE
Collect all questions that have ua ruhr specific content 

### ISSUE THREAD

**Issue by jmfrenzel** [FDM-UARuhr/rdmo-catalog-uaruhr#101]
Collect all questions that have ua ruhr specific content compared to upstream master rdmo-catalog.

* create a new file in rdmorganiser/_changes/changed_questions

**Comment by jmfrenzel** [comment]
check all_questions
* /metadata-and-referencing/structure-granularity-and-referencing/pids/subentities
* /data-usage/data-sharing-and-re-use/interoperability/interoperability
* /legal-and-ethics/sensitive-data-personal_data_yesno/yesno
* /legal-and-ethics/sensitive-data-personal_data/extent
* /legal-and-ethics/sensitive-data-personal_data/bdsg_3_9
* /technical-classification/data/volume/rate
* /metadata-and-referencing/metadata/dataset/standards
* /metadata-and-referencing/metadata/dataset/quality_assurance
* /storage-and-long-term-preservation/long-term-preservation/access_authentication

**Comment by ClaraRosalie** [comment]
I could not find any differences in 
- /metadata-and-referencing/structure-granularity-and-referencing-pids/subentities
- /data-usage/data-sharing-and-re-use-interoperability/interoperability
- /technical-classification/data-volume/rate
- /metadata-and-referencing/metadata-dataset/standards
- /metadata-and-referencing/metadata-dataset/quality_assurance
- /storage-and-long-term-preservation/long-term-preservation-datasets/access_authentication

_____

I would classify 
- legal-and-ethics/sensitive-data-personal_data_yesno/yesno
- legal-and-ethics/sensitive-data-personal_data/extent
- legal-and-ethics/sensitive-data-personal_data/bdsg_3_9 

as UA Ruhr specific because these questions contain links to webpages of UA Ruhr. Surprisingly the upstream master rdmo-catalog contains these links as well - maybe delete them there?
