### ISSUE TITLE
wrong attributes in yaml file

### ISSUE THREAD

**Issue by ClaraRosalie** [FDM-UARuhr/rdmo-catalog-uaruhr#69]
**Describe the bug**
The file [cat_member.yaml](https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/master/tools/cat_member.yaml) contains two question paths ~~attributes~~ that do not exist in UA Ruhr-catalog (on [rdmo-demo](https://rdmo-demo.rd.ruhr-uni-bochum.de/questions/catalogs/7/)): 

- `ua_ruhr/general/funding-funder/funder_policy`
- `ua_ruhr/metadata-and-referencing/metadata/abstract`

Additionally there is one attribute which references a question set rather than a question:
- `ua_ruhr/content-classification/data-reuse`

**Comment by jmfrenzel** [comment]
The file https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/master/tools/cat_member.yaml  references `<path>`variables of questions and not the `<attributes>`.
* Therefore `ua_ruhr/metadata-and-referencing/metadata/abstract` is a valid  `<path>`variable.
* The `<path>`variable  `ua_ruhr/general/funding-funder/funder_policy` is available since https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/releases/tag/1.1.0-beta.1 The 'UA Ruhr' catalog on our rdmo-demo is at release https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/releases/tag/v1.0.0 

The `ua_ruhr/content-classification/data-reuse``<path>` variable references to a   `questionset`. The path variables of `questionset`s are not needed in https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/master/tools/cat_member.yaml and this entry can be deleted, though it does not have any implications on the catalog creation via https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/master/tools/auto_catalog_creation.py
see #70

**Comment by ClaraRosalie** [comment]
Path variable `ua_ruhr/metadata-and-referencing/metadata/abstract` cannot be found on rdmo-demo, but there is a similar variable `ua_ruhr/metadata-and-referencing/metadata-dataset/abstract`. Is this also due to the newer version https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/releases/tag/1.1.0-beta.1?

**Comment by jmfrenzel** [comment]
> The file https://github.com/FDM-UARuhr/rdmo-catalog-uaruhr/blob/master/tools/cat_member.yaml references `<path>`variables of questions and not the `<attributes>`.
> 
>     * Therefore `ua_ruhr/metadata-and-referencing/metadata/abstract` is a valid  `<path>`variable.

Correction:
`ua_ruhr/metadata-and-referencing/metadata/abstract` is not used in any rdmo catalog and therefore can be removed. 

Thanks @ClaraRosalie for spotting this.
